#!/usr/bin/env python

import pickle
import sys
import os
fun_list = []
fun_list2 = []
for filename in os.listdir(sys.argv[1]):
	with open(sys.argv[1] + "/" + filename) as f:
		binaryDict = pickle.load(f)
		for key in binaryDict["functions"].keys():
			fun_list.append(binaryDict["binary_filename"] + ".pkl#" + key)

for filename in os.listdir(sys.argv[2]):
	with open(sys.argv[2] + "/" + filename) as f:
		binaryDict = pickle.load(f)
		for key in binaryDict["functions"].keys():
			fun_list2.append(binaryDict["binary_filename"] + ".pkl#" + key)

splitFuncDict = {
	'train':fun_list
		,
		'test':
		fun_list2
}

pickle.dump(splitFuncDict, open("split_func.pkl","wb"))
		
